# Generated by Django 3.2.11 on 2023-09-17 11:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountdetails_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transfer_code',
            field=models.CharField(blank=True, default='+', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='https://cdn1.iconfinder.com/data/icons/technology-devices-2/100/Profile-512.png', max_length=255, verbose_name='image'),
        ),
    ]
