# Generated by Django 3.2.11 on 2023-09-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_payment_proof_of_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='iban',
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='recipient_bank_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
