# Generated by Django 3.2.11 on 2023-10-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20230917_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cryptowithdraw',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cryptowithdraw',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='diposit',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='interest',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='requested_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paybills',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='support',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='withdrawal_internationa',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
